name: tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: test ${{matrix.tox_env}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: py37
            python: "3.7"
          - tox_env: py38
            python: "3.8"
          - tox_env: py39
            python: "3.9"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Install python for test
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Setup test environment
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: Run test
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}


  check:
    name: check ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - flake8
          - pylint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test environment
        run: tox -vv --notest -e ${{ matrix.tox_env }}
      - name: Run test
        run: tox --skip-pkg-install -e ${{ matrix.tox_env }}

  spell-check:
    name: Spell-Check Repository
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install CSpell Global Configuration
        run: npm --prefix tests/cspell install
      - name: Run CSpell Spell Checker
        run: npm --prefix tests/cspell run cspell

  docs:
    name: docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install base python for tox
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install tox
        run: python -m pip install tox
      - name: Setup test environment
        run: tox -vv --notest -e docs
      - name: Run test
        run: tox --skip-pkg-install -e docs
